### ISSUE TITLE
Use annotation id for relationships

### ISSUE THREAD

**Issue by ar-jan** [CentreForDigitalHumanities/lidia-zotero#48]
Relations to other arguments currently only store the annotation's `zoteroKey` which identifies the publiation or pdf, not the annotation.

Figure out if there's a global id we can use (shared also when syncing via groups), or if it should be zoteroKey + argument name/id.

**Comment by tijmenbaarda** [comment]
This has been fixed, but we still have to find out if the key is stable across different users.
