### ISSUE TITLE
Give all annotations a LIDIA-specific annotation ID

### ISSUE THREAD

**Issue by tijmenbaarda** [CentreForDigitalHumanities/lidia-zotero#68]
Currently we use the Zotero key for cross-references to annotations, but this is problematic because Zotero assigns a different ID when moving items from the local library to a group library. We can solve this by giving all LIDIA annotations a LIDIA-specific unique annotation ID. We may use the `uuid` npm package for unique IDs.

Since users have already been adding cross-references, we need a transition mechanism.

**Comment by ar-jan** [comment]
[ulid](https://github.com/ulid/spec) boasts some advantages over uuid, though it is not used as widely. Do you have an opinion on which is more suitable @jgonggrijp ?
